### ISSUE TITLE
Error when running world server

### ISSUE THREAD

**Issue by altoweb** [wizguin/slippers#2]
**I've installed requirements.txt as it says in the wiki and even if I try running requirements.txt in pip again it says that the requirements are statisfied**
When running `py World.py 1` I get the following error:

`C:\Users\Noah\Desktop\slippers>py World.py 1
[World] Starting world 1
Traceback (most recent call last):
  File "World.py", line 32, in <module>
    main()
  File "World.py", line 28, in main
    World(sys.argv[1], config)
  File "World.py", line 18, in __init__
    self.db = Database(config)
  File "C:\Users\Noah\Desktop\slippers\world\Database.py", line 14, in __init__
    *config["database"].values()))
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\dialects\mysql\mysqlconnector.py", line 129, in dbapi
    from mysql import connector
ModuleNotFoundError: No module named 'mysql'`

**Comment by wizguin** [comment]
This is because SQLAlchemy uses the mysql package, I should probably include this in requirements.txt but for now just install the package manually:

pip3 install --upgrade mysql-connector-python
