### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by Ectalite** [wizguin/slippers#20]
Hello,

I'm using the 2007 media server and configured everything with your wiki.
I'm experiencing some issues: 

- I can't create an account ([Load error](https://imgur.com/mpJnQWU)) 
- I can connect to the test account, but can't connect to a world. [https://imgur.com/CQtOhDi](https://imgur.com/CQtOhDi)

Is there a server I should connect to, to make it work ?

**Comment by Ectalite** [comment]
I got this error recently: 

```
[World] Starting world 1
[Database] Connection successful
[PluginManager] 9 plugins loaded
[Server] Server started on ('127.0.0.1', 6114)
^C[Server] Closing server
Exception during reset or similar
Traceback (most recent call last):
  File "/home/xavier/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/xavier/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/xavier/.local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/base.py", line 2241, in do_rollback
    dbapi_connection.rollback()
  File "/home/xavier/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 403, in rollback
    self._cmysql.rollback()
_mysql_connector.MySQLInterfaceError: MySQL server has gone away
```

**Comment by Ectalite** [comment]
So I found the origin of this error, the mysql.sock was not correctly configured so I changed it in my.cnf file.
So I don't have any error errors anymore but I still can't create an account.

**Comment by Ectalite** [comment]
I found another error while checking the database on phpmyadmin:
`nov. 27 10:44:09 fifouailles phpMyAdmin[11105]: user denied: debian-sys-maint (mysql-denied) from **.***.***.***`

**Comment by wizguin** [comment]
1. The registration won't work, it requires a separate registration server that I haven't written yet. Best option for this would be to insert a new user manually or use a simple PHP login.
2. I haven't used phpmyadmin on linux before so I'm unsure of what that error means, but it [looks like you have to set up the debian-sys-maint user](https://askubuntu.com/questions/329873/mysql-error-1045280000-access-denied-for-user-debian-sys-maint-localhost). Though slippers should still be able to connect through the root user. Can you check the response of login.php in the network tab in the dev console as that will probably give you an error too:
![image](https://user-images.githubusercontent.com/16276645/100514741-1ba71e00-316f-11eb-847b-20011922b8d5.png)

**Comment by Ectalite** [comment]
I'm getting `&e=0` as response

**Comment by wizguin** [comment]
It isn't connecting to the db, have you configured the db in login.php?

**Comment by lucasyrsdr** [comment]
same problem and i config the db
