### ISSUE TITLE
Can't start 2007 server

### ISSUE THREAD

**Issue by KVRX-PI** [wizguin/slippers#32]
Getting a python traceback error when I launch slippers. **/var/www/html/** is my web server directory.

```
pi@raspberrypi:/var/www/html/slippers $ python World.py 1
Traceback (most recent call last):
  File "World.py", line 4, in <module>
    from Server import Server
  File "/var/www/html/slippers/Server.py", line 1, in <module>
    import asyncio
  File "/home/pi/.local/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/home/pi/.local/lib/python2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax

```

**Comment by KVRX-PI** [comment]
Running PHP 7.3, MariaDB, Apache 2 on Raspbian (Linux)

**Comment by wizguin** [comment]
You're using Python 2, you need Python 3

**Comment by KVRX-PI** [comment]
Alright, now i'm doing `python3 World1` and it's saying I don't have xmltodict when I do.

```
pi@raspberrypi:/var/www/html/slippers $ python3 World.py 1
Traceback (most recent call last):
  File "World.py", line 5, in <module>
    from world.DataHandler import DataHandler
  File "/var/www/html/slippers/world/DataHandler.py", line 3, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'

```

**Comment by colleelat** [comment]
You're missing the required modules. Refer to [the Installation page](https://github.com/wizguin/slippers/wiki/Installation).

**Comment by KVRX-PI** [comment]
Oh, everything installed as python 2.7. How do I replace those?
