### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by CraftedRllRl** [wizguin/slippers#41]
Everytime I try to load the server I get an error:

[World] Starting world 1
[Database] Could not connect to MySQL database
(mysql.connector.errors.InterfaceError) 2013: Lost connection to MySQL server during query
(Background on this error at: http://sqlalche.me/e/rvf5)
[PluginManager] 8 plugins loaded
Traceback (most recent call last):
  File "C:\xampped\erm\World.py", line 32, in <module>
    main()
  File "C:\xampped\erm\World.py", line 28, in main
    World(sys.argv[1], config)
  File "C:\xampped\erm\World.py", line 22, in __init__
    super(World, self).__init__(config, world_id, self.users, self.db, self.handler)
  File "C:\xampped\erm\Server.py", line 16, in __init__
    self.server = self.loop.run_until_complete(self.coro)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1491, in create_server
    infos = await tasks.gather(*fs)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1423, in _create_server_getaddrinfo
    infos = await self._ensure_resolved((host, port), family=family,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by CraftedRllRl** [comment]
Fixed by changing port

**Comment by superbird123** [comment]
Wait what port should I be changing and what flies

**Comment by CraftedRllRl** [comment]
> Wait what port should I be changing and what flies

I reinstalled xampp and it fixed itself (i installed 5.6.32)
